# 2. Arrays - Part 1

Make sure that you always first import numpy! 

In [1]:
import numpy

## Create an array
An array is a table of elements. 
An array in Python can be created from a pre-specified list or a tuple with the `array` function. 

An n-dimensional array can also be created from nested lists (tuples)

For more information about creating arrays: 
http://docs.scipy.org/doc/numpy/user/basics.creation.html

In [2]:
# create array from a list:
print( numpy.array([1, 3, 5, 7, 9]) )
print()
# create array from a tuple:
print( numpy.array((2, 4, 6, 8)) )
print()
# 2x2 array
print(numpy.array([[2, 3, 3], [4, 5, 6]]))

[1 3 5 7 9]

[2 4 6 8]

[[2 3 3]
 [4 5 6]]


- `empty` creates an empty array (filled with arbitrary values)
- `zeros` creates an array filled with zeros
- `ones` creates an array filled with ones.
All these functions take the shape of the array as input.  
More about the shape and dimensionality is explained in the next section. 

In [3]:
twoxthree = (2,3)
# create an empty array:
print( numpy.empty(twoxthree) )
print()
# create array with only zeros:
print( numpy.zeros((2,3)) )
print()
# create array with only ones:
print (numpy.ones((2,3)) )

[[  9.88131292e-324   1.48219694e-323   1.48219694e-323]
 [  1.97626258e-323   2.47032823e-323   2.96439388e-323]]

[[ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


To create an array with random numbers use the `numpy.random.random` function which gives an array with numbers between 0 and 1.

The expression `numpy.random.uniform(x, y, z)` returns an array with with shape `z` random numbers uniformly drawn from the interval between `x` and `y`.

In [4]:
# create array with random numbers between 0 and 1:
print(numpy.random.random((2,2)))
print()
# create array with random numbers between 5 and 10:
print( numpy.random.uniform(-1, 1, (2,3)) )

[[ 0.55670023  0.41365267]
 [ 0.2519555   0.00999751]]

[[-0.65232832  0.26043261 -0.04324666]
 [-0.16665235 -0.1286027  -0.70706039]]


In [5]:
print(numpy.random.normal(5, 10, (2,2)))

[[  0.56329082  20.9992465 ]
 [ 18.29030106  11.78672352]]


The identity matrix is a $n \times n$ matrix with all zeros, but with ones on the diagonal. 
The identity matrix can be created with the `eye(n)` function. Since the identity matrix is always a square only one input parameter is needed to create a 2-dimensional matrix.

In [6]:
# create n by n identity matrix:
print( numpy.eye(5))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


Numpy has a function which is similar to the `range` function which is `arange(a, b, s)`, where $a$ is the start point, $b$ is the end point and $s$ is the step size. The function can have floats as inputs.
Another function to create a range is the `linspace(a, b, i)` function, where $a$ is the start point, $b$ is the end point, and $i$ is the number of items.


In [7]:
# use fixed step size:
x = numpy.arange(1.0, 10.0, 2.0)
print(x)

# use fixed number of items:
y = numpy.linspace(1.0, 10.0, 5)
print(y)

[ 1.  3.  5.  7.  9.]
[  1.     3.25   5.5    7.75  10.  ]


## Dimensions

The array class in Python is called "ndarray". 
An array can be 1-dimensional, which is often called a (row or column) vector. By default, a one-dimensional numpy array is a row vector. In order to create a column vector, you need to use a two-dimensional array, with the second dimension equal to 1. See examples below.


An array can be 2-dimensional, where $m$ is the number of rows and $n$ the number of columns. 
In case of a 2-dimensional array, the first dimension is the rows and the second dimension is the columns.

### Bookshelf analogy
An array can be $n$-dimensional. You think of $n$-dimensional arrays in terms of the bookshelf analogy:

- 1d array is a single row of a bookshelf, where a book can be identified by its position in the row
- 2d array is the whole bookshelf, where a book can be identified by its row number and its position in the row
- 3d array is a room full of bookshelves, where a book can be identified by the number of the bookshelf, row, and position in the row
- 4d array is a library with rooms with bookshelves, where a book can be identified by the room, bookshelf, row and position in the row


### Reshaping arrays
A 1D array can be converted to an $n$ dimensional array using the `reshape` function. 

Note that the the total number of elements in the array have to be the same as the product of the lengths of the dimensions. For example, if the length of the list is 24, then we can reshape it to a 4 by 6 matrix, but also to a 2 by 3 by 4 matrix.

Let's assume we have a 2 by 3 by 4 matrix, which we will call `z`. Since the index in Python starts at 0, the first element of the array is `z[0,0,0]`, and the last element of the array is `z[1, 2, 3]`.

Let x be the ndarray. Some important attributes to get insight in the dimensionality:
- `x.ndim` : the number of dimensions.
- `x.shape` : the length of each dimension.
- `x.size` : the total number of elements.

### Create row vectors

In [8]:
a = numpy.zeros((3))
print(a); 
print(a.ndim, a.shape, a.size)

[ 0.  0.  0.]
1 (3,) 3


In [9]:
b = numpy.array([1, 2, 3])
print(b); 
print(b.ndim, b.shape, b.size)

[1 2 3]
1 (3,) 3


In [10]:
c = numpy.zeros((1,3))
print(c)

[[ 0.  0.  0.]]


In [11]:
d = b.reshape((1,3))
print(d.ndim, d.shape, d.size)

2 (1, 3) 3


### Create column vectors

In [12]:
a = numpy.zeros((3, 1))
print(a); 
print(a.ndim, a.shape, a.size)

[[ 0.]
 [ 0.]
 [ 0.]]
2 (3, 1) 3


In [13]:
b_1 = numpy.array([1,2,3])
print(b_1)
print(b_1.ndim)

[1 2 3]
1


In [14]:
b = numpy.array([[1], [2], [3]])
print(b); print(b.ndim, b.shape, b.size)

[[1]
 [2]
 [3]]
2 (3, 1) 3


In [15]:
c_row = numpy.array([1,2,3])
print(c_row)
shape = (3,1)
c = c_row.reshape(shape)
print(c); print(c.ndim, c.shape, c.size)

[1 2 3]
[[1]
 [2]
 [3]]
2 (3, 1) 3


### Create two dimensonal arrays

In [16]:
print( numpy.arange(2, 14, 2).reshape((2, 3)) )

print( numpy.array([[1, 3], [2, 4]]) )

[[ 2  4  6]
 [ 8 10 12]]
[[1 3]
 [2 4]]


In [17]:
# create three dimensional arrays:
z1 = numpy.arange(24).reshape((2, 3, 4))
z2 = numpy.array([[[1, 3], [2, 4]], [[11, 13], [12, 14]] ])

# dimensions/shape/size of the array:
print(z1)
print("Number of dimensions:", z1.ndim)
print("Length of each dimension:", z1.shape)
print("The total number of elements:", z1.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Number of dimensions: 3
Length of each dimension: (2, 3, 4)
The total number of elements: 24


In [18]:
# access some elements in the three dimensional array:
print("First element:", z1[0, 0, 0])
print("Last element:", z1[1, 2, 3])
print("Last element:", z1[-1, -1, -1])

print("Some element:", z1[1, 0, 1])

First element: 0
Last element: 23
Last element: 23
Some element: 13


In [19]:
z1[:, 2:4, :]

array([[[ 8,  9, 10, 11]],

       [[20, 21, 22, 23]]])

In [20]:
# Extract dimensions
a = numpy.random.random(2*3).reshape(2,3)
print(a)
print("First row:\n", a[0, :])
print("Frist row:\n", a[0,])
print("Second column:\n", a[:, 1])
print("First two columns:\n", a[:, 0:2])

[[ 0.63001561  0.32559865  0.88487413]
 [ 0.50785506  0.85748003  0.97088457]]
First row:
 [ 0.63001561  0.32559865  0.88487413]
Frist row:
 [ 0.63001561  0.32559865  0.88487413]
Second column:
 [ 0.32559865  0.85748003]
First two columns:
 [[ 0.63001561  0.32559865]
 [ 0.50785506  0.85748003]]


### Data types

Data types were already discussed in the previous notebook, but here is a small recap. 

One array can only have one data type. 
The data type of the array can be obtained with the `.dtype` attribute. 
In case you mix different data types, the elements are converted to the same type. You can specify the data type of the array when you create the array with the `array` function with the `dtype=` argument.
Example datatypes:

- float (float64)
- integer (int32 or int64)
- boolean (bool)
- complex (complex128)
- string (e.g. `<U16`)

Let assume you created an array `z` with the datatype integer and you want to convert it afterwards to the data type `float`: use the `astype` function. For example, `z.astype('float')` to convert `z` to the data type `float`.

## Exercises

### Exercise 2a.1
Form the 2-D array (without typing it in explicitly):
```python
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
 
 ```
and generate a new array containing its 2nd and 4th rows.
You may find useful the function `numpy.transpose`.

In [21]:
x = numpy.arange(1, 16).reshape((3,5))
y = x.T
print(y)

print(y[1,:])
print(y[3,:])

print()

print(y[[1,3],:])

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[ 2  7 12]
[ 4  9 14]

[[ 2  7 12]
 [ 4  9 14]]


### Exercise 2a.2

Generate a $5\times 5 \times 5$ 3D array of random numbers between -10.0 and 10.0. Reshape it to a $5 \times 25$ matrix, and extract the first two rows of this matrix. 


In [22]:
A = numpy.random.uniform(-10, 10, (5,5,5))
B = A.reshape((5, 25))
print(B[:2, :])

[[-8.27037756  5.59838076  8.4027778  -9.47816417  7.19752176 -5.05232566
  -8.86166223 -2.72151487  7.07990543  7.11261164 -5.6164154  -9.4552296
  -7.5618696  -5.49194121  3.41867158 -3.14635959  9.02791678  6.80906715
  -9.17414527 -6.4165912   3.19542474 -8.83042967 -5.24790378 -0.88993589
   5.43499609]
 [-0.97620814  0.32409734  9.71526082 -3.31314892  2.53758597 -4.86348975
   5.28969095 -0.08619664 -2.93140852 -5.70564086 -4.74731683  9.76073065
   6.60470695  3.15662099 -6.02532857 -6.46224207  1.62459051  9.06111817
   2.64446051 -1.1651946   0.06895026  4.43453132  0.47642886  3.31123013
   1.55094681]]


### Exercise 2a.3

Load the content of the file [populations.txt](populations.txt) into a numpy array. Extract the first column into a vector and assign it to variable named `year`, extract the second column and assign it to variable `hare`, etc for the four columns.

Convert the variables `year` and `carrot` into the datatype `int`.
