# 2. Arrays - Part 2

In [1]:
import numpy

## Structured arrays

A structured array consists of a number of columns, where each column can be a different datatype. 

Full information about structured arrays: 
http://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html#structured-arrays

One of the possible ways to specify a structured array is to use a list of tuples as `dtype`:
For every column in the array a tuple is specified with the name of the column and the type of data in it. For example: 

In [2]:
dtype = [('Name', 'U10'), ('Country', 'U10'), ('Area', 'float64')]

The content of the array can then be given as a list of tuples, like so:

In [3]:
city = numpy.array([('Amsterdam', 'Netherlands', 219.3),
                    ('Paris',     'France',      105.4 ),
                    ('Barcelona', 'Spain',       101.9 )],
                     dtype=dtype)
print(city)

[('Amsterdam', 'Netherland',  219.3) ('Paris', 'France',  105.4)
 ('Barcelona', 'Spain',  101.9)]


### Indexing structured arrays
The rows in a structured array can be accessed by regular indexing. The columns of the array by using the column names that are specified when the array was created.

In [4]:
# Access first row
print(city[0])

('Amsterdam', 'Netherland',  219.3)


In [5]:
# Access first two rows
print(city[0:2])

[('Amsterdam', 'Netherland',  219.3) ('Paris', 'France',  105.4)]


In [6]:
# Access column by name
print(city['Area'])

[ 219.3  105.4  101.9]


In [7]:
# Access two columns using list of names
print(city[['Name', 'Area']])

[('Amsterdam',  219.3) ('Paris',  105.4) ('Barcelona',  101.9)]


In [8]:
print(city[['Name', 'Country']])

[('Amsterdam', 'Netherland') ('Paris', 'France') ('Barcelona', 'Spain')]


In [9]:
# Print information about the array
print(city.shape, city.dtype)

(3,) [('Name', '<U10'), ('Country', '<U10'), ('Area', '<f8')]


Note that structured arrays like this one, even though they have rows and columns, 
are treated as one-dimensional.

### Accessing and modifying column names

For example:


In [10]:
city.dtype.names

('Name', 'Country', 'Area')

In [11]:
city.dtype.names = ('name', 'country', 'area')
print(city['area'])

[ 219.3  105.4  101.9]


### Loading data into structured arrays

Structured arrays are useful for loading and working with tabular data with heterogeneous column types. 

#### Exercise 2b.1

Complete the following code loading the data from file [populations.txt](populations.txt). Load the year column as an `int`, and the other columns as `float`.

In [12]:
dtype = [('year', 'int'),
         ('hare', 'float'),
         ('lynx', 'float'),
         ('carrot', 'float')
         ] 
population = numpy.loadtxt("populations.txt", dtype=dtype)
print(population.dtype)          

[('year', '<i8'), ('hare', '<f8'), ('lynx', '<f8'), ('carrot', '<f8')]


An alternative way of loading tabular data using `genfromtxt`:

In [13]:
population = numpy.genfromtxt("populations.txt", 
                 names=True,
                 dtype=['int','float','float','float'])
# Access lynx column

print(population.dtype)

[('year', '<i8'), ('hare', '<f8'), ('lynx', '<f8'), ('carrot', '<f8')]


### Record arrays
There is a special interface to structured arrays called **record arrays**. For details, see https://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html#record-arrays

## Array Indexing

For complete information  about indexing see
http://docs.scipy.org/doc/numpy/user/basics.indexing.html

You have already seen how to access content of the array by using an index for each dimension. This method is know as matrix indexing. In addition to matrix indexing, there are other ways to address content in an array

- Linear indexing transforms an n-dimensional array to a 1-dimensional list. This linear index is returned when the `argmin` and `argmax` function are applied to an n-dimensional array. 

In [14]:
a = numpy.random.uniform(-1, 1, (5,5))
print(a)
# Return the index of the maximum value
numpy.argmax(a)

[[ 0.34287301  0.09903818  0.6689162  -0.4643664  -0.54364808]
 [ 0.89682901 -0.99975489  0.42351741 -0.35578959  0.18684122]
 [ 0.77249366 -0.65664591 -0.30753702 -0.44424554 -0.03534377]
 [ 0.47377239 -0.88246203 -0.46674585  0.71299917  0.79879941]
 [-0.41181842  0.66289824  0.60433942  0.81616188 -0.06268194]]


5

- Boolean indexing, which returns all values in the array for which the index is True.

In [15]:
a = numpy.random.uniform(-1, 1, (5,5))
# Create a boolean index for positive numbers in array a
print(a)
index = a > 0.0
print(index)
# Return all the positive numbers
print(a[:,0][index[:,0]])

[[ 0.50058289 -0.78704983 -0.18227432  0.48676769  0.68720613]
 [-0.25243017 -0.57001704  0.67542694 -0.25171337 -0.44224427]
 [-0.11004441  0.95053005  0.63107112  0.90637761 -0.50126632]
 [ 0.28017502  0.10809428  0.78257892  0.25415453 -0.33194622]
 [ 0.83089174  0.71162136  0.53646652  0.12881724  0.62692707]]
[[ True False False  True  True]
 [False False  True False False]
 [False  True  True  True False]
 [ True  True  True  True False]
 [ True  True  True  True  True]]
[ 0.50058289  0.28017502  0.83089174]


- Indexing with an array of indices. In this case you specify a separate array in which you store the indices as integers and you will return exactly the elements of the array with these indices. 

In [16]:
b = numpy.linspace(0,1,10)
print(b)
# Return numbers at prime indices
index = numpy.array([ 2, 3, 5, 7])
print(b[index])

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]
[ 0.22222222  0.33333333  0.55555556  0.77777778]


### Linear and matrix indexing

Indexing in a 1-dimensional matrix is similar as indexing in a Python list. 

Indexing in a n-dimensional matrix has one index for every dimension. To access one element of the array, the index of every dimension should be given. When accessing more than one element, the slice syntax `m:n` can be used, and this works similar as it works with lists, but you can use the `m:n` for every dimension. 

If the index is `[m:n]` then indices that are used are `m` up to but not including `n`.

If you have the linear index and you want to convert it to a matrix index, you can use the function `numpy.unravel_index()`.

The first argument is the linear index and the second argument is the shape of the array for which you want to transform the index. For example: `numpy.unravel_index(linear_index, (2,3))`. 

In [17]:
# indexing in a 3-dimensional array
z = numpy.arange(24).reshape((2, 3, 4))
print(z)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [18]:
# slices
print(z[0:2, 1:3, 3])
print(z[:, 2, :])

[[ 7 11]
 [19 23]]
[[ 8  9 10 11]
 [20 21 22 23]]


In [19]:
# linear indexing
linear_index = 10
print("\n For a array with dimensions (2, 3, 4), the linear index: ", linear_index, " is equal to \
multidimensional index: ", numpy.unravel_index(linear_index, z.shape))


 For a array with dimensions (2, 3, 4), the linear index:  10  is equal to multidimensional index:  (0, 2, 2)


#### Exercise 2b.2

Create a $4\times3$ matrix of random numbers between $0$ and $1$. 
Find the row and column position of the minimum and the maximum value.

In [20]:
A = numpy.random.uniform(0, 1, (4, 3))
print(A)

[[ 0.42083886  0.13756153  0.13565775]
 [ 0.51541557  0.81532107  0.22389037]
 [ 0.55850363  0.47145112  0.67892257]
 [ 0.37072193  0.28585296  0.71058531]]


In [21]:
largest = numpy.argmax(A)
smallest = numpy.argmin(A)
print("Largest value is at linear position {}".format(largest))
row, col = numpy.unravel_index(largest, A.shape)
print("Which is row {} column {}".format(row, col))


Largest value is at linear position 4
Which is row 1 column 1


#### Exercise 2b.3 

Complete the following code to print years with the smallest number of hares, lynxes and carrots in the 
populations dataset.

In [22]:
for species in ['carrot', 'hare', 'lynx']:
    year = population['year'][ population[species].argmin() ]
    print("Least # of {} in year {}".format(species, year))

Least # of carrot in year 1916
Least # of hare in year 1917
Least # of lynx in year 1900


### Boolean indexing

A boolean index can be created directly, but most often it is built by specifying a certain condition.

The condition will return a `True` or `False` for every position in the array and when the condition is True then the corresponding element will be retrieved.

In [23]:
# Boolean indexing
x = numpy.arange(1, 6)
y = numpy.array([True, False, True, False, True ])
print("Only elements of x for which the value in y is True: ", x[y])

# boolean indexing by using a condition
print("Only elements of x for which the condition is True: ", x[x>3])

Only elements of x for which the value in y is True:  [1 3 5]
Only elements of x for which the condition is True:  [4 5]


#### Exercise 2b.4
Use the population data to

1. Select all the years in which there are more than 50000 lynxes;
2. Select all the years in which there are more lynxes than hares.

In [24]:
# 1.
index = population['lynx'] > 50000
years = population['year'][index]
print(years)
print()

#2.
index = population['lynx'] > population['hare']
years = population['year'][index]
print(years)

[1904 1915]

[1904 1905 1906 1915 1916 1917]


### Indexing with an array of indices

In this case you specify a separate array in which you store the indices as integers and you will return exactly the elements of the array with these indices.

One advantage of this is that you can explicitly specify the order in which you want to have the values and you can return multiple times the value at a certain position. 

In [25]:
x = numpy.arange(100, 111)
y = numpy.array([8, 3, 8, 4, 9, 3])
print("Array x: ", x)
print("Array with indices: ", y)
print("Indexing with an array of indices will give:", x[y])

Array x:  [100 101 102 103 104 105 106 107 108 109 110]
Array with indices:  [8 3 8 4 9 3]
Indexing with an array of indices will give: [108 103 108 104 109 103]


#### Exercise 2b.5

Indexing with an array is often useful when we want to randomize the order of items in some data. Complete the following code which creates a scrambled version of the population data

In [26]:
# Create an index for the rows of population (from 0 to population.shape[0])
index = numpy.arange(0, population.shape[0])
#print(index)
# Shuffle the index
numpy.random.shuffle(index)
#print(index)
# Create a scrambled version
population_rand = population[index]
print(population['year'])
print(population_rand['year'])

[1900 1901 1902 1903 1904 1905 1906 1907 1908 1909 1910 1911 1912 1913 1914
 1915 1916 1917 1918 1919 1920]
[1920 1909 1908 1901 1903 1904 1913 1915 1914 1905 1917 1912 1907 1911 1902
 1906 1900 1918 1919 1916 1910]


## Vector stacking

Sometimes you want to combine two or more vectors to create an array. This is called vector stacking. Vector stacking can be done in two different ways horizontal and vertical. 
- horizontal stack: `numpy.hstack([x, y, z])`
- vertical stack: `numpy.vstack([x, y, z])`

In [27]:
x = numpy.arange(0, 5)                     
y = numpy.arange(5, 10)   
z = numpy.arange(10, 15)
print("Horizontal stack: ",  numpy.hstack([x,y, z]) )
print("Vertical stack: ")
print( numpy.vstack([x,y, z]))

Horizontal stack:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Vertical stack: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### Save data set to file

To save an array from numpy as a separate file you specify the filename and the array you want to save. Use the following functions:
- `numpy.savetxt(filename, array)` : save an array to a text file. Some optional arguments are: delimiter=' ', newline = '\n', header = ' '. http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.savetxt.html#numpy.savetxt
- `numpy.save(filename, array)` : save an array to a binary file in numpy `.npy` format. http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.save.html#numpy.save


#### Exercise 2b.6 

Save the population data to a `.npy` file. Figure out how to load it back into a numpy array.

In [28]:
numpy.save("population.npy", population)
zzz = numpy.load("population.npy")
print(zzz['lynx'])

[  4000.   6100.   9800.  35200.  59400.  41700.  19000.  13000.   8300.
   9100.   7400.   8000.  12300.  19500.  45700.  51100.  29700.  15800.
   9700.  10100.   8600.]


#### Exercise 2b.7
The files

- [irisa.txt](irisa.txt)
- [irisb.txt](irisb.txt)
- [irisc.txt](irisc.txt)

contain the data for the iris dataset. Each file has these columns:

- `SepalLength` 
- `SepalWidth`
- `PetalLength` 
- `PetalWidth` 
- `Species`

Load this data, and create a single array with all the species.