# 4. Linear algebra operations

In [1]:
import numpy

## Basic operations

Linear algebra is a branch of mathematics dealing with vector spaces. Linear algebra operations such as transposes, dot products, matrix multiplications and others are often very useful when manipulating numeric datasets. Using these operations often allows us to avoid writing explicit loops, and thus make our code more readable, more concise and faster to execute.

In the following steps we'll implement linear regression using `numpy` linear algebra operations. We will start with the functional form of the regression: how the predicted target values depend on the regression coefficients the of features (aka predictors or regressors). 

Once we have the coefficients $\mathrm{\beta}$ and the matrix with the predictors $\mathrm{X}$ we can calculate predicted targets $\mathrm{\hat{y}}$ according to:

$$
\mathrm{\hat{y}} = \beta_0 + \mathrm{X}\mathrm{\beta}
$$

If we add an extra column with all $1$s to the matrix $\mathrm{X}$, we can write this without the intercept $\beta_0$:

$$
\mathrm{\hat{y}} = \mathrm{X}\mathrm{\beta}
$$

This operation is the matrix multiplication. In this case the first matrix is $N\times M$ where N is the number datapoints (rows) and $M$ the number of predictors (including the extra row of ones). The second matrix is $M\times 1$, so it is a column vector.

In this particular case, for each row of M we multiply it with $\beta$ and the sum these multiplications is our predicted $\hat{y}$ for each row. This can be written explicitly as:

$$
\mathrm{\hat{y}_i} = \sum_{m=1}^M X_{i,m} \beta_m
$$

We can see that the matrix multiplication version is much more concise. The same is true in numpy code: it's more concise to implement this using the matrix multiplication function `numpy.dot` than write a bunch of loops.


### Matrix multiplication / dot product

In numpy the concept of dot product (aka scalar product) is treated as
a special case of matrix multiplication. The numpy function `dot` for simple dot product between vectors, for multiplying a matrix by a vector, as well as for multyplying two matrices.

The definition of dot product between two vectors $u$ and $v$ is:

$$\langle u, v\rangle = \sum_{i=1}^N u_i v_i$$

Other notations that you will come across for this operation are:
$u \cdot v$, $u^T v$.

In numpy we write
```python
numpy.dot(u, v)
```
or
```python
u.dot(v)
```

#### Exercise 4.1

Create two vectors of random values between -10 and 10 of size 100. Compute:
- elementwise product between them
- dot (scalar) product between them.


In [2]:
u = numpy.random.uniform(-10, 10, 100)
v = numpy.random.uniform(-10, 10, 100)


In [3]:
print((u * v).sum())
print()
print(u.dot(v))

-406.095054309

-406.095054309


When multiplying two matrices, the number of columns in the first one needs to be equal to the number of rows in the second one. For matrices $A_{m\times n}$ and $B_{n \times p}$, the resulting matrix will be $C_{m \times p}$. It is defined as:

$$
C_{i,j} = \sum_{k=1}^n A_{i,k}B_{k,j}
$$
![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/470px-Matrix_multiplication_diagram_2.svg.png)

In `numpy` we simply use `dot`:

```python
numpy.dot(A, B)
```
or

```python
A.dot(B)
```

### Exercise 4.2

- Create a random matrix $A_{3\times 4}$ and another random matrix $B_{4 \times 2}$. Multiply AB.  

In [4]:
A = numpy.random.normal(0, 1, (3, 4))
B = numpy.random.normal(0, 1, (4, 2))
print(A.dot(B))

[[-0.88518703  4.05587537]
 [-1.30617896  1.24515244]
 [-0.01976229  0.48491352]]


- Create a random matrix $C_{3\times 3}$ and $D_{3\times3}$. Multiply CD. Multiply DC. Is matrix multiplication commutative?

In [5]:
C = numpy.random.normal(0, 1, (3, 3))
D = numpy.random.normal(0, 1, (3, 3))
print(C.dot(D))
print(D.dot(C))

[[ 1.41704317 -3.58252534  1.56000168]
 [-0.42751905  3.93881925 -0.21749712]
 [-1.64386228 -0.85783927 -1.39472289]]
[[-0.01354687 -1.82658323  0.57374335]
 [ 0.0866353   2.10414174 -2.10526647]
 [ 1.2434547  -2.0753115   1.87054466]]


- Create a identity matrix $I_{3\times 3}$.  Multiply IC, CI, DI, ID. What do you notice?

In [6]:
I = numpy.eye(3)
print(I)
print(C)
print(I.dot(C))
print(C.dot(I))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.24877402 -1.73729257  0.94931267]
 [-0.32831221  1.43190608 -1.35595747]
 [-1.23894356 -0.20189761 -0.03416515]]
[[ 1.24877402 -1.73729257  0.94931267]
 [-0.32831221  1.43190608 -1.35595747]
 [-1.23894356 -0.20189761 -0.03416515]]
[[ 1.24877402 -1.73729257  0.94931267]
 [-0.32831221  1.43190608 -1.35595747]
 [-1.23894356 -0.20189761 -0.03416515]]


- What will be the result of multiplying a matrix $Z_{m\times n}$ by a matrix $O_{n \times p}$ whose all entries are zero? Check your answer using some examples in `numpy`.

In [7]:
O = numpy.zeros((4, 3))
print(O)
print(A.dot(O))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


### Exercise 4.3

- Create a random matrix $A_{3\times 4}$ and another random matrix $B_{2 \times 4}$. Can you transform one of them so that they can be multiplied? Try this in `numpy`.

In [8]:
import numpy.random as R
A = R.uniform(-1,1,(3,4))
B = R.uniform(-2,2,(2,4))
print(A.dot(B.T))

[[-0.96175767 -0.19951327]
 [-0.47592575  0.06210395]
 [ 0.58492503  1.18858648]]


## Transpose

We have already encountered matrix transpose. The mathematical notation for the transpose of matrix $A$ is $A^T$. Transposing a matrix simply means making the rows into columns and columns into rows. If $A$ is $m \times n$ then $A^T$ is $n \times m$. The values are:

$$A^T_{i,j} = A_{j,i}$$

In `numpy` the transpose is simply written `A.T`.

### Exercise 4.4

- Create a random $4 \times 5$ matrix and verify that the above equality holds for it.
- What would be the outcome of $(A^T)^T$? Check this in `numpy`.

In [9]:
A = numpy.random.normal(1, 0, (4,5))
for i in range(4):
    for j in range(5):
        print(A[i,j] == A.T[j,i])

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [10]:
print(numpy.allclose(A.T.T, A))

True


## Inverse

For scalar numbers the multiplicative inverse (aka reciprocal) of number $n$ is $\frac{1}{n}$, also written as $n^{-1}$. This inverse has certain properties, like:
- $n^{-1}n = 1$
- $(n^{-1})^{-1} = n$

There is an analogous concept for matrices. For a square matrix $A_{m \times m}$, its inverse is written $A^{-1}$ and it satisfies:

- $A^{-1}A = I$ where $I$ is the $m \times m$ identity matrix
- $(A^{-1})^{-1} = A$
- $(A^T)^{-1} = (A^{-1})^T$

Not all matrices are invertible: a matrix needs to be square, and its [determinant](https://en.wikipedia.org/wiki/Determinant) needs to be non-zero. There is a function to invert matrices in `scipy.linalg` called `inv`.


In [11]:
from scipy.linalg import inv
A = numpy.random.uniform(0,1,(3,3))
print(A)
print(inv(A))

[[ 0.66094125  0.3807814   0.38991002]
 [ 0.21474223  0.78247872  0.11353492]
 [ 0.06067056  0.25141203  0.38733982]]
[[ 1.77184864 -0.31923176 -1.69003431]
 [-0.49236455  1.49957138  0.05608551]
 [ 0.04204918 -0.92332959  2.81002547]]


- $A^{-1}A = I$ where $I$ is the $m \times m$ identity matrix
- $(A^{-1})^{-1} = A$
- $(A^T)^{-1} = (A^{-1})^T$

### Exercise 4.5

Verify the three properties of the matrix inverse operations listed above for a random $m \times m$ numpy matrix. 

In [12]:
A = numpy.random.normal(0, 1, (5, 5))
print(numpy.allclose(  inv(A).dot(A),    numpy.eye(5)         ))
print(numpy.allclose(  inv(inv(A)),      A                    ))
print(numpy.allclose(  inv(A.T),         inv(A).T             ))

True
True
True


In [13]:
print(numpy.allclose( inv(A).dot(A),  numpy.eye(5)))

True


## Ordinary Least Squares formula for Linear Regression

We are now ready to implement the formula which can be used to find the coefficients of linear regression:

$$\hat\beta = (X^TX)^{-1}X^Ty$$

Remember that $X$ has $N$ rows corresponding to the $N$ datapoints, and $M$ columns corresponding to the $M$ predictors. The formula defines the vector $\hat\beta$ with the $M$ regression coefficients.

We will apply this formula to the winequality dataset.

Previously we loaded this dataset into a structured array.


In [14]:
# Load winequality as a structured array
data = numpy.genfromtxt("winequality-red.csv", names=True, delimiter=';')
# Convert the array into a matrix. We'll have the target in the last column
print(data.shape)

(1599,)


In [15]:
# Convert structured array into array of numeric values
Xy = data.view((data.dtype[0], len(data.dtype)))
print(Xy.shape)

(1599, 12)


In [16]:
# Extract X and y from Xy
X = Xy[:,:-1]
y = Xy[:,-1:]
print(X.shape)
print(y.shape)

(1599, 11)
(1599, 1)


In [17]:
X_new = numpy.hstack([ numpy.ones((1599,1)), X ])
print(X_new)

[[  1.      7.4     0.7   ...,   3.51    0.56    9.4  ]
 [  1.      7.8     0.88  ...,   3.2     0.68    9.8  ]
 [  1.      7.8     0.76  ...,   3.26    0.65    9.8  ]
 ..., 
 [  1.      6.3     0.51  ...,   3.42    0.75   11.   ]
 [  1.      5.9     0.645 ...,   3.57    0.71   10.2  ]
 [  1.      6.      0.31  ...,   3.39    0.66   11.   ]]


### Exercise 4.6

Implement function `fit` which takes a matrix of predictors and a vector of targets, and returns the vector of regression coefficients computed according to the OLS formula.
Apply this function to the winequality data.

$$(X^T X)^{-1} X^T y$$

In [18]:
def fit(X, y):
    # ----------------------------------
    return inv(X.T.dot(X)).dot(X.T).dot(y)


In [19]:
beta = fit(X_new, y)
print(beta)

[[  2.19652084e+01]
 [  2.49905526e-02]
 [ -1.08359026e+00]
 [ -1.82563948e-01]
 [  1.63312698e-02]
 [ -1.87422516e+00]
 [  4.36133331e-03]
 [ -3.26457970e-03]
 [ -1.78811638e+01]
 [ -4.13653144e-01]
 [  9.16334413e-01]
 [  2.76197699e-01]]


In [20]:
fit(X[:,:3], y)

array([[ 0.54531392],
       [ 1.93350958],
       [-0.2695241 ]])

### Exercise 4.7

Implement function `predict` which takes a vector of coefficients and a vector of predictors, and returns the predicted targets according to the regression formula (see beginning of notebook). Apply this function to the coefficients from the previous exercise, and the winequality data.

In [21]:
def predict(beta, X):
    #--------------------------------
    return X.dot(beta)


In [22]:
beta = fit(X_new, y)
y_pred = predict(beta, X_new)
print(numpy.hstack([ y, y_pred]))

[[ 5.          5.03285045]
 [ 5.          5.13787975]
 [ 5.          5.20989474]
 ..., 
 [ 6.          5.94304255]
 [ 5.          5.47075621]
 [ 6.          6.00819633]]


### Exercise 4.8

Define the following two functions to quantify how well the regression is able to predict the targets:
- `mse` - mean squared error, defined as the mean of the squared difference between each prediction and true target: $$MSE(y, \hat{y}) = \frac{1}{N}\sum_{i=1}^N (y_i-\hat{y}_i)^2$$
- `mae` - mean absolute error, defined as the mean of the absolute difference between each prediction and true target: $$MAE(y, \hat{y}) = \frac{1}{N}\sum_{i=1}^N abs(y_i-\hat{y}_i)$$

Check how well your regression functions predict the targets in winequality according to these error measures.

In [23]:
def mse(y, y_pred):
    return numpy.mean((y - y_pred)**2)
def mse_silly(y, y_pred):
    return numpy.sum((y - y_pred)**2)/len(y)
def mae(y, y_pred):
    return numpy.mean(numpy.abs(y - y_pred))


In [24]:
print(mse(y, y_pred))
print(mse_silly(y, y_pred))

0.416767167221
0.416767167221


### Exercise 4.9

- Load the iris data and extract the first three column into a predictor matrix, and the fourth column into a target vector. Apply the functions `fit` and `predict` to this data, and check the MSE and MAE of your predictions.